// Decompiled with JetBrains decompiler
// Type: Windows.Foundation.Diagnostics.CausalitySource
// Assembly: Windows.Foundation.UniversalApiContract, Version=14.0.0.0, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime
// MVID: F62EFE2D-E4C7-4EB8-B17A-E7D33D1BB49F
// Assembly location: C:\Users\codyc\.nuget\packages\microsoft.windows.sdk.contracts\10.0.22000.196\ref\netstandard2.0\Windows.Foundation.UniversalApiContract.winmd

using Windows.Foundation.Metadata;

namespace Windows.Foundation.Diagnostics
{
  /// <summary>Provides flags that listeners use to filter tracing events.</summary>
  [ContractVersion(typeof (UniversalApiContract), 65536)]
  public enum CausalitySource
  {
    /// <summary>Indicates causality information generated by app-defined asynchronous operations.</summary>
    Application,
    /// <summary>Indicates causality information generated by language projections or asynchronous infrastructure libraries.</summary>
    Library,
    /// <summary>Indicates causality information generated by Windows.</summary>
    System,
  }
}
