// Decompiled with JetBrains decompiler
// Type: Windows.System.Profile.SystemIdentificationSource
// Assembly: Windows.Foundation.UniversalApiContract, Version=14.0.0.0, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime
// MVID: F62EFE2D-E4C7-4EB8-B17A-E7D33D1BB49F
// Assembly location: C:\Users\codyc\.nuget\packages\microsoft.windows.sdk.contracts\10.0.22000.196\ref\netstandard2.0\Windows.Foundation.UniversalApiContract.winmd

using Windows.Foundation;
using Windows.Foundation.Metadata;

namespace Windows.System.Profile
{
  /// <summary>Indicates the module used to generate a unique system identifier.</summary>
  [ContractVersion(typeof (UniversalApiContract), 196608)]
  public enum SystemIdentificationSource
  {
    /// <summary>There is no module present on the device for generating a unique system ID.</summary>
    None,
    /// <summary>The ID was generated by a Trusted Platform Module (TPM).</summary>
    Tpm,
    /// <summary>The ID was generated by a Unified Extensible Firmware Interface (UEFI).</summary>
    Uefi,
    /// <summary>The ID was generated from the system registry.</summary>
    [ContractVersion("Windows.Foundation.UniversalApiContract", 327680)] Registry,
  }
}
