// Decompiled with JetBrains decompiler
// Type: Windows.UI.Input.SystemButtonEventController
// Assembly: Windows.Foundation.UniversalApiContract, Version=14.0.0.0, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime
// MVID: F62EFE2D-E4C7-4EB8-B17A-E7D33D1BB49F
// Assembly location: C:\Users\codyc\.nuget\packages\microsoft.windows.sdk.contracts\10.0.22000.196\ref\netstandard2.0\Windows.Foundation.UniversalApiContract.winmd

using System.Runtime.CompilerServices;
using Windows.Foundation;
using Windows.Foundation.Metadata;
using Windows.System;

namespace Windows.UI.Input
{
  /// <summary>Enables an application to handle events generated by system keyboard buttons (such as the Function keys).</summary>
  [WebHostHidden]
  [MarshalingBehavior(MarshalingType.Agile)]
  [Static(typeof (ISystemButtonEventControllerStatics), 655360, "Windows.Foundation.UniversalApiContract")]
  [ContractVersion(typeof (UniversalApiContract), 655360)]
  [Threading(ThreadingModel.Both)]
  public sealed class SystemButtonEventController : 
    AttachableInputObject,
    ISystemButtonEventController
  {
    /// <summary>Occurs when a Function (also know as Function Shift) key is pressed.</summary>
    public extern event TypedEventHandler<SystemButtonEventController, SystemFunctionButtonEventArgs> SystemFunctionButtonPressed;

    /// <summary>Occurs when a Function (also know as Function Shift) key, which is currently pressed, is released.</summary>
    public extern event TypedEventHandler<SystemButtonEventController, SystemFunctionButtonEventArgs> SystemFunctionButtonReleased;

    /// <summary>Occurs on changes to the state of the Function (also know as Function Shift) key lock.</summary>
    public extern event TypedEventHandler<SystemButtonEventController, SystemFunctionLockChangedEventArgs> SystemFunctionLockChanged;

    /// <summary>Occurs on changes to the state of the visual indicator for the Function (also know as Function Shift) key lock.</summary>
    public extern event TypedEventHandler<SystemButtonEventController, SystemFunctionLockIndicatorChangedEventArgs> SystemFunctionLockIndicatorChanged;

    /// <summary>Creates a SystemButtonEventController object on the specified dispatcher queue.</summary>
    /// <param name="queue">The DispatcherQueue for managing prioritized tasks that execute in a serial fashion on a thread.</param>
    /// <returns>A SystemButtonEventController.</returns>
    [MethodImpl]
    public static extern SystemButtonEventController CreateForDispatcherQueue(
      DispatcherQueue queue);
  }
}
