// Decompiled with JetBrains decompiler
// Type: Windows.Media.Capture.AdvancedCapturedPhoto
// Assembly: Windows.Foundation.UniversalApiContract, Version=14.0.0.0, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime
// MVID: F62EFE2D-E4C7-4EB8-B17A-E7D33D1BB49F
// Assembly location: C:\Users\codyc\.nuget\packages\microsoft.windows.sdk.contracts\10.0.22000.196\ref\netstandard2.0\Windows.Foundation.UniversalApiContract.winmd

using System.Runtime.CompilerServices;
using Windows.Foundation;
using Windows.Foundation.Metadata;
using Windows.Media.Devices;

namespace Windows.Media.Capture
{
  /// <summary>Represents a photo captured using system-provided computational photography techniques provided by the AdvancedPhotoCapture class.</summary>
  [ContractVersion(typeof (UniversalApiContract), 65536)]
  [DualApiPartition(version = 167772160)]
  [MarshalingBehavior(MarshalingType.Agile)]
  [GCPressure(amount = GCPressureAmount.High)]
  [Threading(ThreadingModel.Both)]
  public sealed class AdvancedCapturedPhoto : IAdvancedCapturedPhoto, IAdvancedCapturedPhoto2
  {
    /// <summary>Gets the captured frame containing the result of the advanced photo capture.</summary>
    /// <returns>The captured frame containing the result of the advanced photo capture.</returns>
    public extern CapturedFrame Frame { [MethodImpl] get; }

    /// <summary>Gets a value indicating the advanced capture mode with which the photo was captured.</summary>
    /// <returns>A value indicating the advanced capture mode with which the photo was captured.</returns>
    public extern AdvancedPhotoMode Mode { [MethodImpl] get; }

    /// <summary>Gets the app-defined context object associated with the advanced photo capture operation, if one was provided in the call to AdvancedPhotoCapture.CaptureAsync(Object).</summary>
    /// <returns>The app-defined context object associated with the advanced photo capture operation.</returns>
    public extern object Context { [MethodImpl] get; }

    /// <summary>Gets a reference to a Rect that expresses the dimensions of the Frame generated by the advanced photo capture operation, relative to the reference photo passed into the OptionalReferencePhotoCaptured event.</summary>
    /// <returns>A reference to a Rect that expresses the frame bounds of the captured frame relative to a reference photo.</returns>
    public extern IReference<Rect> FrameBoundsRelativeToReferencePhoto { [MethodImpl] get; }
  }
}
