// Decompiled with JetBrains decompiler
// Type: Windows.UI.Input.Inking.Analysis.IInkAnalysisNode
// Assembly: Windows.Foundation.UniversalApiContract, Version=14.0.0.0, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime
// MVID: F62EFE2D-E4C7-4EB8-B17A-E7D33D1BB49F
// Assembly location: C:\Users\codyc\.nuget\packages\microsoft.windows.sdk.contracts\10.0.22000.196\ref\netstandard2.0\Windows.Foundation.UniversalApiContract.winmd

using Windows.Foundation;
using Windows.Foundation.Collections;
using Windows.Foundation.Metadata;

namespace Windows.UI.Input.Inking.Analysis
{
  /// <summary>Represents a single node from the tree of objects generated by the ink analysis process. </summary>
  [ContractVersion(typeof (UniversalApiContract), 262144)]
  [Guid(813899525, 24420, 18988, 186, 55, 79, 72, 135, 135, 149, 116)]
  public interface IInkAnalysisNode
  {
    /// <summary>Gets the unique identifier of a single node belonging to the IInkAnalysisNode object.</summary>
    /// <returns>
    /// </returns>
    uint Id { get; }

    /// <summary>Gets the kind of ink input identified by ink analysis for the IInkAnalysisNode object.</summary>
    /// <returns>
    /// </returns>
    InkAnalysisNodeKind Kind { get; }

    /// <summary>Gets the position and size of a single node belonging to the IInkAnalysisNode object.</summary>
    /// <returns>The X, Y coordinates (top left) and dimensions (length and width) of the bounding box for the IInkAnalysisNode object, in device-independent pixels (DIPs) relative to the upper left-hand corner of the inking area.</returns>
    Rect BoundingRect { get; }

    /// <summary>Gets the oriented and snapped, bounding rectangle of a single node belonging to the IInkAnalysisNode object. </summary>
    /// <returns>The X, Y coordinates for each vertex point of the bounding box for the IInkAnalysisNode object, in device-independent pixels (DIPs) relative to the upper left-hand corner of the inking area.</returns>
    IVectorView<Point> RotatedBoundingRect { get; }

    /// <summary>Gets all child nodes of a single node belonging to the IInkAnalysisNode object.</summary>
    /// <returns>
    /// </returns>
    IVectorView<IInkAnalysisNode> Children { get; }

    /// <summary>Gets the parent node of the IInkAnalysisNode object.</summary>
    /// <returns>
    /// </returns>
    IInkAnalysisNode Parent { get; }

    /// <summary>Retrieves the unique identifiers of all nodes belonging to the IInkAnalysisNode object.</summary>
    /// <returns>Type: IVectorView&lt;uint&gt;  </returns>
    IVectorView<uint> GetStrokeIds();
  }
}
