// Decompiled with JetBrains decompiler
// Type: Windows.ApplicationModel.Background.BackgroundTaskProgressEventArgs
// Assembly: Windows.Foundation.UniversalApiContract, Version=14.0.0.0, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime
// MVID: F62EFE2D-E4C7-4EB8-B17A-E7D33D1BB49F
// Assembly location: C:\Users\codyc\.nuget\packages\microsoft.windows.sdk.contracts\10.0.22000.196\ref\netstandard2.0\Windows.Foundation.UniversalApiContract.winmd

using System;
using System.Runtime.CompilerServices;
using Windows.Foundation;
using Windows.Foundation.Metadata;

namespace Windows.ApplicationModel.Background
{
  /// <summary>Represents progress information for a task at the time a progress update notification is sent.</summary>
  [Threading(ThreadingModel.Both)]
  [MarshalingBehavior(MarshalingType.Agile)]
  [ContractVersion(typeof (UniversalApiContract), 65536)]
  public sealed class BackgroundTaskProgressEventArgs : IBackgroundTaskProgressEventArgs
  {
    /// <summary>Gets the identifier of the background task instance for this progress status notification.</summary>
    /// <returns>A unique identifier generated by the system when it creates the background task instance.</returns>
    public extern Guid InstanceId { [MethodImpl] get; }

    /// <summary>Gets progress status for a background task instance.</summary>
    /// <returns>A value defined by the application to indicate the task's progress.</returns>
    public extern uint Progress { [MethodImpl] get; }
  }
}
